project:
  name: DownloaderService

localfilder: /Users/pierre/dev/

servers:
  timeout: 20000
  list:
    - http://apache.mirror.globo.tech//httpd/httpd-2.4.33.tar.bz2
    - ftp://speedtest.tele2.net/5MB.zip#anonymous#
    - sftp://test.rebex.net/readme.txt#demo#password
    - http://releases.ubuntu.com/14.04.3/ubuntu-14.04.3-desktop-amd64.iso